import {test} from 'node:test';
import assert from 'node:assert/strict';
import {initialState,legalMoves,pseudoMoves,applyAction,inCheck,allMoves,positionKey} from '../src/game/rules.js';
import {GameStore} from '../src/game/store.js';
const piece=(type,color='white',id=1)=>({type,color,id});
function position(entries,turn='white'){const s={...initialState(),board:Array(64).fill(null),turn};for(const [i,type,color] of entries)s.board[i]=piece(type,color,Number(i));s.positions=[positionKey(s)];return s;}
test('traditional initial army and asymmetric king placement',()=>{const s=initialState();assert.equal(s.board.filter(Boolean).length,32);assert.equal(s.board[3].type,'K');assert.equal(s.board[60].type,'K');assert.equal(s.board[4].type,'M');assert.equal(s.board[59].type,'M');for(let i=16;i<24;i++)assert.equal(s.board[i].type,'P');assert.equal(allMoves(s).length,23);});
test('Bia single step, diagonal capture, no double advance',()=>{const s=initialState();assert.deepEqual(legalMoves(s,16),[24]);s.board[25]=piece('P','black');assert.deepEqual(legalMoves(s,16),[24,25]);s.board[24]=piece('P','black');assert.deepEqual(legalMoves(s,16),[25]);});
test('Met and promoted Bia move only one diagonal',()=>{for(const type of ['M','F']){const s=position([[3,'K','white'],[60,'K','black'],[27,type,'white']]);assert.deepEqual(legalMoves(s,27).sort((a,b)=>a-b),[18,20,34,36]);}});
test('Khon forward is relative to color',()=>{for(const color of ['white','black']){const s=position([[3,'K','white'],[60,'K','black'],[27,'S',color]],color);assert.deepEqual(legalMoves(s,27).sort((a,b)=>a-b),color==='white'?[18,20,34,35,36]:[18,19,20,34,36]);}});
test('Ma leaps over blockers; Ruea stops at blockers',()=>{const s=initialState();assert.deepEqual(legalMoves(s,1),[11]);const b=Array(64).fill(null);b[27]=piece('R');b[29]=piece('P');b[43]=piece('P','black');const moves=pseudoMoves(b,27);assert(moves.includes(28));assert(!moves.includes(29));assert(moves.includes(43));assert(!moves.includes(51));});
test('pins and checked kings filter legal moves',()=>{const s=position([[3,'K','white'],[11,'R','white'],[59,'R','black'],[63,'K','black']]);assert(!legalMoves(s,11).includes(12));assert(legalMoves(s,11).includes(19));s.board[11]=null;assert(inCheck(s.board,'white'));assert(!legalMoves(s,3).includes(11));});
test('kings cannot be adjacent or captured',()=>{const s=position([[27,'K','white'],[43,'K','black']]);assert(!legalMoves(s,27).includes(35));const invalid=position([[27,'K','white'],[28,'K','black']]);assert(!legalMoves(invalid,27).includes(28));});
test('both colors promote automatically on sixth rank',()=>{for(const [from,to,color] of [[32,40,'white'],[31,23,'black']]){const s=position([[0,'K','white'],[63,'K','black'],[from,'P',color]],color);const n=applyAction(s,{type:'MOVE',from,to});assert.equal(n.board[to].type,'F');assert(n.history[0].promoted);assert.equal(s.board[from].type,'P');}});
test('turn enforcement, immutable captures, undo and reset',()=>{const store=new GameStore();assert.throws(()=>store.dispatch({type:'MOVE',from:40,to:32}));const before=JSON.stringify(store.state);store.dispatch({type:'MOVE',from:16,to:24});assert.equal(store.state.turn,'black');store.undo();assert.equal(JSON.stringify(store.state),before);store.reset();assert.equal(store.snapshots.length,0);const s=position([[0,'K','white'],[63,'K','black'],[24,'R','white'],[32,'S','black']]);const n=applyAction(s,{type:'MOVE',from:24,to:32});assert.equal(n.history[0].captured.type,'S');assert.equal(s.board[32].color,'black');});
test('checkmate and stalemate end the game',()=>{const mate=position([[0,'K','black'],[18,'K','white'],[9,'R','white'],[16,'R','white']]);const n=applyAction(mate,{type:'MOVE',from:16,to:8});assert.equal(n.result?.winner,'white');assert.equal(n.result?.reason,'Checkmate');const stale=position([[0,'K','black'],[18,'K','white'],[17,'M','white'],[19,'M','white']]);const d=applyAction(stale,{type:'MOVE',from:19,to:10});assert.equal(d.result?.reason,'Stalemate');});
test('honor counting uses minimum material limit, fixed after capture',()=>{const s=position([[0,'K','white'],[63,'K','black'],[54,'S','black'],[53,'N','black'],[52,'N','black']]);const n=applyAction(s,{type:'MOVE',from:0,to:1});assert.equal(n.count.limit,32);assert.equal(n.count.value,5);assert.equal(n.count.color,'white');const next=applyAction(n,{type:'MOVE',from:63,to:62});assert.equal(next.count.value,5);const next2=applyAction(next,{type:'MOVE',from:1,to:0});assert.equal(next2.count.value,6);});
test('board honor can start and stop and opponent can accept',()=>{let s=position([[0,'K','white'],[63,'K','black'],[8,'M','white'],[55,'M','black']]);s=applyAction(s,{type:'COUNT'});assert.equal(s.count.limit,64);s=applyAction(s,{type:'MOVE',from:8,to:17});assert.equal(s.count.value,1);assert.equal(applyAction(s,{type:'DRAW'}).result.winner,null);assert.throws(()=>applyAction(initialState(),{type:'COUNT'}));});
test('count expiration and threefold repetition draw',()=>{let s=position([[0,'K','white'],[63,'K','black'],[8,'M','white'],[55,'M','black']]);s.count={kind:'board',color:'white',value:64,limit:64};assert.equal(applyAction(s,{type:'MOVE',from:8,to:17}).result.reason,'Honor count exhausted');s=position([[0,'K','white'],[63,'K','black'],[8,'M','white'],[55,'M','black']]);for(let i=0;i<2;i++)for(const [from,to] of [[0,1],[63,62],[1,0],[62,63]])s=applyAction(s,{type:'MOVE',from,to});assert.equal(s.result.reason,'Threefold repetition');});
