import './style.css';
import * as THREE from 'three';
import {GameStore} from './game/store.js';
import {legalMoves,inCheck,NAMES} from './game/rules.js';
import {World} from './scene/world.js';
import {CameraRig} from './scene/camera.js';
import {Effects} from './scene/effects.js';
import {Animator} from './scene/animation.js';
import {mount,renderUI} from './ui.js';
mount();const $=id=>document.getElementById(id),store=new GameStore();let selected=null,moves=[],toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
let world;
try{world=new World($('scene'));}catch(error){$('status').textContent='WebGL is unavailable.';$('toast').textContent='Please enable hardware acceleration or use a WebGL-capable browser.';$('toast').classList.add('show');throw error;}
const rig=new CameraRig(world,locked=>{$('crosshair').hidden=!locked;$('look').textContent=locked?'Esc to release mouse':'Enter mouse look ↗';}),effects=new Effects(world.scene),animator=new Animator(world,effects,rig);
function refresh(){world.highlight(selected,moves,store.state);renderUI(store,selected,moves);}
store.subscribe((s,action)=>{selected=null;moves=[];if(action.type!=='MOVE'){effects.clear();world.sync(s,{resetFacing:action.type==='RESET'||action.type==='UNDO'});}refresh();});world.sync(store.state);refresh();world.resize();new ResizeObserver(()=>world.resize()).observe($('scene'));
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();let down=null;
$('scene').addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY,time:performance.now()};});
$('scene').addEventListener('pointerup',e=>{if(e.button!==0||!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6||performance.now()-down.time>500)return;down=null;if(animator.busy||store.state.result)return;const rect=$('scene').getBoundingClientRect();if(document.pointerLockElement)$('crosshair').hidden=false;mouse.set(document.pointerLockElement?0:(e.clientX-rect.left)/rect.width*2-1,document.pointerLockElement?0:-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(mouse,world.camera);
 const hits=raycaster.intersectObjects([...world.tiles,...world.pieces.values()],true);if(!hits.length){selected=null;moves=[];refresh();return;}let object=hits[0].object;while(object&&object.userData.square===undefined)object=object.parent;if(!object)return;const index=object.userData.square;
 if(selected!==null&&moves.includes(index)){const next=store.dispatch({type:'MOVE',from:selected,to:index});const move=next.history.at(-1);$('undo').disabled=true;$('new-game').disabled=true;animator.move(move,()=>{world.sync(next);refresh();$('new-game').disabled=false;if(next.result)toast(next.result.winner?`${next.result.winner==='white'?'Ivory':'Obsidian'} wins by ${next.result.reason.toLowerCase()}.`:`Draw · ${next.result.reason}`);else if(inCheck(next.board,next.turn))toast('Check — protect your Khun.');else if(move.promoted)toast('Bia awakened — promoted to Bia Ngai.');});return;}
 const p=store.state.board[index];if(p?.color===store.state.turn){selected=index;moves=legalMoves(store.state,index);if(!moves.length)toast(`${NAMES[p.type]} has no legal moves.`);}else{selected=null;moves=[];if(p)toast(`It is ${store.state.turn==='white'?'Ivory':'Obsidian'}’s turn.`);}refresh();});
function cameraMode(mode){rig.setMode(mode);$('orbit').classList.toggle('active',mode==='orbit');$('fly').classList.toggle('active',mode==='fly');$('look').hidden=mode!=='fly';$('camera-hint').textContent=mode==='fly'?'WASD · Shift · Space / Ctrl':'Drag to orbit · Scroll to explore';if(mode==='fly')toast('WASD to fly · Space / Ctrl for height · Enter mouse look to explore.');}
$('orbit').onclick=()=>cameraMode('orbit');$('fly').onclick=()=>cameraMode('fly');$('look').onclick=()=>document.pointerLockElement?document.exitPointerLock():rig.lock();window.addEventListener('keydown',e=>{if(e.code==='KeyV'&&!e.repeat&&!document.querySelector('dialog[open]'))cameraMode(rig.mode==='orbit'?'fly':'orbit');});$('home').onclick=()=>{cameraMode('orbit');rig.home();};$('sound').onclick=()=>{effects.muted=!effects.muted;$('sound').innerHTML=effects.muted?'♫<span class="mute-slash">/</span>':'♫';$('sound').setAttribute('aria-label',effects.muted?'Enable sound':'Mute sound');if(!effects.muted)effects.sound();toast(effects.muted?'Sound muted':'Sound enabled');};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Fullscreen is unavailable in this browser.');}};
$('rules').onclick=()=>{document.exitPointerLock?.();rig.keys.clear();$('guide').showModal();};document.querySelector('.close').onclick=()=>$('guide').close();$('new-game').onclick=()=>{if(animator.busy)return;if(!store.state.ply){store.reset();toast('A new legend begins.');}else $('new-dialog').showModal();};$('confirm-new').onclick=()=>{store.reset();$('new-dialog').close();toast('A new legend begins.');};document.querySelector('.close-new').onclick=()=>$('new-dialog').close();$('undo').onclick=()=>{if(!animator.busy){store.undo();toast('Last action undone.');}};$('count').onclick=()=>{if(!animator.busy)store.dispatch({type:'COUNT'});};$('accept-draw').onclick=()=>{if(!animator.busy)store.dispatch({type:'DRAW'});};
let last=performance.now(),elapsed=0;function frame(now){const dt=Math.min((now-last)/1000,.04);last=now;elapsed+=dt;world.update(elapsed);animator.update(dt);effects.update(dt);rig.update(dt,elapsed);world.render();requestAnimationFrame(frame);}requestAnimationFrame(frame);
