import {NAMES,inCheck,square} from './game/rules.js';
export const icons={K:'♔',M:'♕',S:'♗',N:'♘',R:'♖',P:'♙',F:'♙'};
export function mount(){document.querySelector('#app').innerHTML=`
 <header class="topbar"><a class="brand" href="./"><span class="brand-mark">♜</span><span>MAKRUK<small>THE TEMPLE OF KINGS</small></span></a><nav><span class="nav-active">The battlefield</span><button id="rules">How to play <span>↗</span></button></nav><div class="edition"><i></i> A timeless game. Reawakened.</div></header>
 <main><section class="arena"><canvas id="scene" aria-label="Interactive 3D Makruk board"></canvas><div class="scene-shade"></div><div class="scene-title"><div class="eyebrow">ANCIENT SIAM · A NEW CHAPTER</div><h1>The Temple<br>of Kings<span>.</span></h1><p>Stone remembers. Your move makes history.</p></div><div class="live-label"><i></i> LOCAL TWO-PLAYER <span>01 / THE SANCTUARY</span></div>
 <div class="view-tools"><button id="home" title="Reset camera" aria-label="Reset camera">⌂</button><button id="sound" title="Toggle sound" aria-label="Enable sound">♫<span class="mute-slash">/</span></button><button id="fullscreen" title="Toggle fullscreen" aria-label="Toggle fullscreen">⛶</button></div>
 <div id="crosshair" hidden>+</div><div id="toast" role="status"></div><div class="camera-bar"><div class="camera-toggle"><button id="orbit" class="active">◉ <span>Orbit</span></button><button id="fly">✥ <span>Free fly</span></button></div><span id="camera-hint">WASD to move / Drag to orbit <b>·</b> Scroll to explore</span><button id="look" hidden>Enter mouse look ↗</button><span class="keycap">V</span></div>
 <div class="scene-bottom"><span>หมากรุกไทย</span><span>STRATEGY, CARVED IN STONE</span></div></section>
 <aside class="sidebar"><div class="game-heading"><div><div class="eyebrow">THE MATCH</div><h2>A battle of legacies</h2></div><span class="ornament">❖</span></div>
 <div class="player black"><div class="avatar">♚</div><div><h3>Obsidian dynasty</h3><span>Black pieces</span></div><span id="black-turn" class="turn-label">WAITING</span></div><div class="captured" id="black-captured">No pieces captured</div>
 <div class="turn-card"><span class="turn-symbol" id="turn-symbol">♔</span><div><div class="eyebrow" id="turn-title">IVORY TO MOVE</div><p id="status">Let your story unfold.</p></div><span class="turn-dot"></span></div>
 <div class="player white"><div class="avatar">♔</div><div><h3>Ivory kingdom</h3><span>White pieces</span></div><span id="white-turn" class="turn-label current">YOUR TURN</span></div><div class="captured" id="white-captured">No pieces captured</div>
 <div class="history-heading"><h3>Move chronicle</h3><span id="move-number">00 MOVES</span></div><div id="history" aria-live="polite"><div class="empty-history"><span>⌁</span><p>Every legend begins<br>with a single move.</p></div></div>
 <div id="selection"><span class="selection-icon">◇</span><div><strong>The board awaits</strong><p>Select a piece to see its legal moves.</p></div></div><div class="actions"><button id="new-game" class="primary">New game <span>↗</span></button><button id="undo" disabled>↶ &nbsp; Undo</button></div><button id="count" class="text-button" hidden>Start honor count</button><button id="accept-draw" class="text-button" hidden>Accept counting draw</button><div class="match-footer"><span>◈ &nbsp; Traditional Makruk rules</span><span>8 × 8</span></div></aside></main>
 <footer><span>AN ANCIENT RIVALRY. AN IMMERSIVE WORLD.</span><span>Made for the thoughtful move. <span class="footer-star">✦</span></span></footer>
 <dialog id="guide"><button class="close" aria-label="Close guide">×</button><div class="eyebrow">THE ART OF THAI CHESS</div><h2>Know your kingdom.</h2><p>Two players share this device. Ivory moves first. Select a piece, then a marked square. Protect your Khun and checkmate the opposing king.</p><div class="rule-grid">${[['K','King','One square in any direction. No castling.'],['M','Counsellor','One square diagonally.'],['S','Guardian','One square diagonally, or one square forward.'],['N','Horse','An L-shaped leap: two squares, then one across.'],['R','Boat','Any distance horizontally or vertically.'],['P','Shell','One step forward; capture diagonally forward. No double step.']].map(([t,n,d])=>`<div><span>${icons[t]}</span><strong>${NAMES[t]} · ${n}</strong><p>${d}</p></div>`).join('')}</div><p><strong>Promotion.</strong> Bia become Bia Ngai (moving as Met) on rank 6 for Ivory and rank 3 for Obsidian. Kings start on d1 and e8; Bia start on ranks 3 and 6.</p><p><strong>Draws.</strong> Stalemate, bare kings, and threefold repetition draw automatically. Without unpromoted Bia, a disadvantaged player can start a 64-move honor count on their turn. The opponent can accept a draw. A bare king automatically starts piece counting: 8 / 16 for two / one Ruea; 22 for two Khon; 32 for two Ma; 44 for one Khon; otherwise 64. It starts at the total remaining pieces; each escaping move increments it. The limit stays fixed. Exceeding the limit draws.</p><p><strong>Explore.</strong> Orbit: WASD or arrows to move, Shift to move faster, drag to rotate, right-drag to pan, scroll to zoom. Free fly: WASD or arrows, Shift to sprint, Space / Ctrl up / down. Enter mouse look, then click the centered piece or square to play. Esc releases the mouse. V switches modes. Scroll adjusts flight speed.</p><p class="source">Counting convention follows <a href="https://www.pychess.org/variants/makruk" target="_blank" rel="noreferrer">PyChess Makruk</a>. All art is original procedural geometry.</p></dialog>
 <dialog id="new-dialog"><div class="eyebrow">A NEW CHAPTER</div><h2>Begin again?</h2><p>This will clear the current match and its move chronicle.</p><div class="actions"><button id="confirm-new" class="primary">Begin new game</button><button class="close-new">Keep playing</button></div></dialog>`;}
export function renderUI(store,selected,moves){const s=store.state,white=s.turn==='white',check=inCheck(s.board,s.turn);document.querySelector('#turn-title').textContent=s.result?(s.result.winner?`${s.result.winner==='white'?'IVORY':'OBSIDIAN'} WINS`:'MATCH DRAWN'):`${white?'IVORY':'OBSIDIAN'} TO MOVE`;document.querySelector('#turn-symbol').textContent=white?'♔':'♚';document.querySelector('#status').textContent=s.result?s.result.reason:check?'Check. Protect your Khun.':s.count?`${s.count.kind==='piece'?'Piece':'Board'} honor · ${s.count.value} / ${s.count.limit}`:s.ply?'The next chapter is yours.':'Let your story unfold.';
 for(const color of ['white','black']){const current=s.turn===color&&!s.result;const label=document.querySelector(`#${color}-turn`);label.classList.toggle('current',current);label.textContent=current?'YOUR TURN':s.result?'FINISHED':'WAITING';const taken=s.history.filter(m=>m.captured&&m.piece.color===color);document.querySelector(`#${color}-captured`).textContent=taken.length?taken.map(m=>icons[m.captured.type]).join(' '):'No pieces captured';}
 document.querySelector('#move-number').textContent=`${String(s.ply).padStart(2,'0')} MOVES`;const history=document.querySelector('#history');if(s.history.length){history.innerHTML=Array.from({length:Math.ceil(s.history.length/2)},(_,i)=>`<div class="history-row"><span>${String(i+1).padStart(2,'0')}</span>${[s.history[i*2],s.history[i*2+1]].map(m=>`<span>${m?`${icons[m.piece.type]} ${square(m.from)} ${m.captured?'×':'–'} ${square(m.to)}${m.promoted?' ↑':''}`:'—'}</span>`).join('')}</div>`).join('');history.scrollTop=history.scrollHeight;}else history.innerHTML='<div class="empty-history"><span>⌁</span><p>Every legend begins<br>with a single move.</p></div>';
 const piece=s.board[selected];document.querySelector('#selection').innerHTML=piece?`<span class="selection-icon">${icons[piece.type]}</span><div><strong>${NAMES[piece.type]} <small>· ${square(selected)}</small></strong><p>${moves.length} legal ${moves.length===1?'move':'moves'} · choose a marked square.</p></div>`:'<span class="selection-icon">◇</span><div><strong>The board awaits</strong><p>Select a piece to see its legal moves.</p></div>';document.querySelector('#undo').disabled=!store.snapshots.length;const count=document.querySelector('#count');count.hidden=!!s.result||s.board.some(p=>p?.type==='P')||s.count?.kind==='piece';count.textContent=s.count?'Stop honor count':'Start honor count';document.querySelector('#accept-draw').hidden=!!s.result||!s.count||s.count.color===s.turn;
}
